CREATE TABLE tb_estudantes(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
idade INT NOT NULL,
numero_sala  INT NOT NULL,
telefone VARCHAR(255) NOT NULL UNIQUE,
media DECIMAL(2,1) NOT NULL
);
